volumes:
  db_data:
  static:
  media:

services:
  web:
    container_name: referral_project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || true &&
      python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_new
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"