# Generated by Django 5.1.6 on 2025-02-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referralcode_code_referralrelations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcode',
            options={'verbose_name': 'Реферальный код', 'verbose_name_plural': 'Реферальные коды'},
        ),
    ]
