# Generated by Django 5.1.6 on 2025-02-25 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_alter_referralrelations_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Дата окончания действия кода'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
